# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483ccfd8674517209e3f1fe066bc8cb2b140d49f42478a7e551aa77001c856d26550c6976df724165428b70b972799d0431dfa2ac9d719d475056f0184ad11da

test:
  secret_key_base: 04e468de45a37204b959035da441c9203116ed3991003b967c08bb959bbaa35fc8782a7a9c68ba0064038ca0c79dc52416aafcfa11e734fba8370958ff2880a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
